config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  devise_for :users
  
  resources :tasks do
    member do
      patch :complete
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  
  def completed?
		!completed_at.blank?
	end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index
    if user_signed_in?
      @tasks = Task.where(:user_id => current_user.id).order("created_at DESC")
    end
  end

  def show
  end

  def new
    @task = current_user.tasks.build
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to root_path
    else
      render 'new'
  end
end

  def edit
  end

  def update
    if @task.update(task_params)
			redirect_to task_path(@task)
		else
			render 'edit'
		end
	end

  def destroy
		@task.destroy
		redirect_to root_path
	end

  def complete
		@task = Task.find(params[:id])
		@task.update_attribute(:completed_at, Time.now)
		redirect_to root_path
	end

  private

  def task_params
    (params.require(:task).permit(:title, :description))
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Edynak ToDo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  </head>

  <body>

    	<nav class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <%= link_to "Edynak ToDo List", root_path, class:"navbar-brand" %>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li>
                <%= link_to current_user.email, user_session_path(current_user.email), class: 'nav-link' %>
              </li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Log In", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>
          </ul>
          <% if user_signed_in? %>
            <%= link_to "Create New Task", new_task_path, class: "navbar-text navbar-link" %>
          <% end %>
        </div>
      </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/index.html.erb
<% if user_signed_in? %>
<%controller.redirect_to tasks_path %>
<% else %>
  <div class="jumbotron">
    <h2>Welcome to Edynak ToDo List</h2>
    <h4>Trusted by millions. Edynak ToDo List is the best online Task Management App!</h4>
    <br>
    <h5>Please register an account or sign in to continue</h5>
    <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>
    <%= link_to "Login", new_user_session_path, class: 'btn btn-success' %>
</div>
<% end %>

app/views/tasks/_form.html.erb
<%= simple_form_for @task do |f| %>
	<%= f.input :title, label: "Task Title" %>
	<%= f.input :description %>
	<%= f.button :submit %>
<% end %>

app/views/tasks/edit.html.erb
<div class="col-md-8 col-md-offset-2">
	<h1>Edit ToDo Task</h1>

	<%= render 'form' %>
</div>

app/views/tasks/index.html.erb
<!-- Checks to see if a user is signed in, if one is, it will list its checklist. -->
<!-- If not, it will render the landing page that asks the user to sign up or login. -->
<% if user_signed_in? %>
	<div class="col-md-10 col-md-offset-1">
		<% @tasks.each do |task| %> 
			<div class="task-wrapper">
				
				<% if task.completed? %>
<!-- For Completed Tasks-->
					<div class="row task">

						<div class="col-md-2">
							<p><%= link_to complete_task_path(item), method: :patch do %></p>
								<i class="fa fa-check fa-lg"></i>
							<% end %>
						</div>
			
						<div class="col-md-2">
							<p><%= link_to task, method: :delete, data: { confirm: "Are you sure?" } do %></p>
								<i class="fa fa-trash fa-lg"></i>
							<% end %>
						</div>

						<div class="col-md-8">
							<h2 style="opacity: 0.5;" class="task-title"><strike><%= link_to task.title, task %></strike></h2>
							<p style="opacity: 0.5;" class="task-sub-title task-desc"><%= item.description %></p>
							<p style="opacity: 0.5;" class="time-created-at task-sub-title">Completed <%= time_ago_in_words(item.completed_at) %> ago</p>
						</div>
							
					</div>

				<% else %>
<!-- NOT Completed -->

					<div class="row task">

						<div class="col-md-2">
							<p><%= link_to complete_task_path(task), method: :patch do %></p>
								<i class="fa fa-check fa-lg"></i>
							<% end %>
						</div>

						<div class="col-md-8">
							<h2 class="task-title"><%= link_to task.title, task %></h2>
							<p class="task-sub-title task-desc"><%= task.description %></p>
							<p style="opacity: 0.5;" class="time-created-at task-sub-title">Created <%= time_ago_in_words(task.created_at) %> ago</p>
						</div>
						
						<div class="col-md-2">
							<p><%= link_to task, method: :delete, data: { confirm: "Are you sure?" } do %></p>
								<i class="fa fa-trash fa-lg"></i>
							<% end %>
						</div>
					</div>

				<% end %>
			</div>
		<% end %>	
	</div>
<% else %>
<% end %>

app/views/tasks/new.html.erb
<div class="col-md-8 col-md-offset-2">
	<h1>New Todo Task</h1>

	<%= render 'form' %>
</div>

app/views/tasks/show.html.erb
<div class="col-md-10 col-md-offset-1">
	<h2><%= @task.title %></h2>
	<p><%= @task.description %></p>
	<div class="user">
		<p>Task posted by user:</p>
		<%= link_to @task.user.email, user_session_path(@task.user.email) %>
	</div>

	<div class="col-md-4 col-md-offset-4">
		<%= link_to "Back", root_path %>
		<%= link_to "Edit", edit_task_path(@task) %>
		<%= link_to "Delete", task_path(@task), method: :delete, data: { confirm: "Are you sure?" } %>
	</div>

</div>